version: "4"

services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - "./server:/app"
    env_file:
      - .env
    environment:
      - APP_SETTINGS=app.config.DevConfig
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@api-db:${POSTGRES_PORT}/${POSTGRES_DB}
      - DATABASE_TEST_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@api-db:${POSTGRES_PORT}/${POSTGRES_TEST_DB}
    depends_on:
      - api-db

  api-db:
    build:
      context: ./server/app/db
      dockerfile: Dockerfile
    container_name: api-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - api-db:/var/lib/postgresql/data



volumes:
  api-db: