version: "4"

services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "${FLASK_PORT:5000}:${FLASK_PORT:5000}"
    volumes:
      - "./server:/app"
    env_file:
      - .env
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db

  api-db:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    container_name: api-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - note-db:/var/lib/postgresql/data
      - ./server/db/create.sql:/docker-entrypoint-initdb.d



volumes:
  note-db: