FROM python:3.11-slim-buster

WORKDIR /app

# System dependencies
RUN apt-get update \
    && apt-get -y install netcat gcc postgresql libpq-dev \
    && apt-get clean

# Application dependencies
RUN pip install --upgrade pip
COPY requirements.txt /app
RUN pip install -r requirements.txt

# Add app
COPY . /app

# Expose port
EXPOSE 5000

# Run server
CMD gunicorn -b 0.0.0.0:5000 manage:app